name: Chrome

on:
  push:
    branches:
      - main  # or specify other branches you want to trigger the workflow

jobs:
  chrome:
    runs-on: ubuntu-22.04
    name: E2E on Chrome

    steps:
      # Step 1: Checkout the repository code
      - uses: actions/checkout@v4

      # Step 2: Set up Cypress and run tests using Chrome
      - uses: cypress-io/github-action@v6
        with:
          browser: chrome  # This ensures Cypress runs in Chrome
