name: NPM Run Workflow

on:
  push:
    branches:
      - feature/runner  # Trigger the workflow on push to this branch

  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - qa
          - uat
          - e2e
          - prod

jobs:
  npm-run:
    name: NPM Run on ${{ inputs.environment }}
    # runs-on: ${{ matrix.runner }}
    runs-on: self-hosted

    # strategy:
    #   matrix:
    #     environment: [dev, qa, uat, e2e, prod]
    #     include:
    #       - environment: dev
    #         runner: self-hosted
    #       - environment: qa
    #         runner: self-hosted
    #       - environment: uat
    #         runner: self-hosted
    #       - environment: e2e
    #         runner: self-hosted
    #       - environment: prod
    #         runner: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run NPM script
        run: npm run build
        env:
          NODE_ENV: ${{ matrix.environment }}
