name: NPM Run Workflow

on:
  push:
    branches:
      - feature/runner-2  # Trigger the workflow on push to this branch

  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: e2e
        type: choice
        options:
          - dev
          - qa
          - uat
          - e2e
          - prod

jobs:
  restart-app:
    name: Deployment restart for ${{ matrix.env }}
    runs-on: 
      - self-hosted
      - cnative
      - common-runners
      - ${{ matrix.dynamic-runner }}
    strategy:
      matrix:
        include:
          - env: qa
            dynamic-runner: dev-qa
          - env: dev
            dynamic-runner: dev-qa
          - env: uat
            dynamic-runner: uat
          - env: e2e
            dynamic-runner: e2e
          - env: prod
            dynamic-runner: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install
