name: K8 Deploy

on:
  workflow_call:
    inputs:
      DEPLOY_ENVIRONMENT:
        required: true
        type: string

jobs:
  deploy-K8:
    name: "Deploy k8 ${{ inputs.DEPLOY_ENVIRONMENT }}"
    runs-on: >-
      ${{ inputs.DEPLOY_ENVIRONMENT == 'dev' || inputs.DEPLOY_ENVIRONMENT == 'qa' && '["self-hosted", "cnative", "dev-qa", "common-runners"]'
      || inputs.DEPLOY_ENVIRONMENT == 'uat' && '["self-hosted", "cnative", "uat", "shared-runners"]'
      || inputs.DEPLOY_ENVIRONMENT == 'e2e' && '["self-hosted", "cnative", "e2e", "shared-runners"]'
      || inputs.DEPLOY_ENVIRONMENT == 'prod' && '["self-hosted", "cnative", "prod", "shared-runners"]' }}
    environment: ${{ inputs.DEPLOY_ENVIRONMENT }}
    permissions:
      contents: 'read'
      # id-token: 'write'
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      # - name: Debug Environment
      #   run: echo "Running on environment: ${{ inputs.DEPLOY_ENVIRONMENT }}"
